### ISSUE TITLE
Forge SSL implementation fails to parse certificate list for COMODO InstantSSL certs

### ISSUE THREAD

**Issue by lizthegrey** [flackr/circ#338]
Socket Error: tlsError: Could not parse certificate list.

is the error message displayed when attempting to connect to irc.of-sound-mind.com:6697 after we replaced our previous SSL certificate with a COMODO wildcard SSL certificate.

both Chrome and OpenSSL are happy with the certificate/chain, so this is a bug in Forge SSL.

**Comment by m-p-3** [comment]
Also unable to connect to
/server alt.irc.snoonet.org +443
Socket Error: tlsError: Could not parse certificate list.

 Comodo SSL fingerprint
2E:A7:4F:9E:A0:2B:F9:1B:05:6F:5D:D9:DC:B3:4F:0C:DF:02:B4:C0

**Comment by jcmdln** [comment]
Hasn't been any forward movement on this for a while now, so I'm going to haphazardly investigate and attempt a few things. I'll try to put relevant information into this issue while I'm fiddling around.

```
Unchecked runtime.lastError while running sockets.tcp.close: Socket not found
    at SslSocket.window.net.SslSocket.SslSocket._close (chrome-extension://bebigdkelppomhhjaaianniiifjbgocn/bin/net/ssl_socket.js:153:26)
    at Object.error (chrome-extension://bebigdkelppomhhjaaianniiifjbgocn/bin/net/ssl_socket.js:132:17)
    at Object.error (chrome-extension://bebigdkelppomhhjaaianniiifjbgocn/bin/third_party/forge/tls.js:3638:15)
    at _readRecordHeader (chrome-extension://bebigdkelppomhhjaaianniiifjbgocn/bin/third_party/forge/tls.js:3735:11)
    at Object.c.process (chrome-extension://bebigdkelppomhhjaaianniiifjbgocn/bin/third_party/forge/tls.js:3922:16)
    at chrome-extension://bebigdkelppomhhjaaianniiifjbgocn/bin/net/ssl_socket.js:176:43
    at arrayBuffer2String (chrome-extension://bebigdkelppomhhjaaianniiifjbgocn/bin/net/ssl_socket.js:29:5)
```
